# `Searching dataframes`

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('Pokemon.csv')

In [3]:
# searching DataFrame
df.loc[df['Name'].str.contains('Hundoom')]

Empty DataFrame
Columns: [#, Name, Type 1, Type 2, Total, HP, Attack, Defense, Sp. Atk, Sp. Def, Speed, Generation, Legendary]
Index: []

In [4]:
df.loc[df['Name'].str.contains('Sableye') & (df['Total'] > 390)]

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
327,302,SableyeMega Sableye,Dark,Ghost,480,50,85,125,85,115,20,3,False

In [5]:
df.loc[df['Name'].str.contains('Sableye')]

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
326,302,Sableye,Dark,Ghost,380,50,75,75,65,65,50,3,False
327,302,SableyeMega Sableye,Dark,Ghost,480,50,85,125,85,115,20,3,False

In [6]:
import re
df.loc[df['Type 1'].str.contains('Grass|Ghost', regex=True)]

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
48,43,Oddish,Grass,Poison,320,45,50,55,75,65,30,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
783,710,PumpkabooSuper Size,Ghost,Grass,335,59,66,70,44,55,41,6,False
784,711,GourgeistAverage Size,Ghost,Grass,494,65,90,122,58,75,84,6,False
785,711,GourgeistSmall Size,Ghost,Grass,494,55,85,122,58,75,99,6,False
786,711,GourgeistLarge Size,Ghost,Grass,494,75,95,122,58,75,69,6,False
787,711,GourgeistSuper Size,Ghost,Grass,494,85,100,122,58,75,54,6,False